### ISSUE TITLE
PyPardiso can't locate shared library 'mkl_rt.dll' on Windows with MKL version 2021.2.0

### ISSUE THREAD

**Issue by haasad** [haasad/PyPardisoProject#12]
On windows pypardiso can't be imported with the newest version of MKL [2021.2.0](https://anaconda.org/conda-forge/mkl)
```
FileNotFoundError: Could not find module 'mkl_rt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
There must have been a change in how mkl is packaged between these versions, which throws off pypardiso. This used to work without problems until now. `ctypes` just found the library in the path, see the relevant [code here](https://github.com/haasad/PyPardisoProject/blob/f666ea4718b32fa1359e5ca94bedac710b09a428/pypardiso/pardiso_wrapper.py#L66).

[mkl 2020.2](https://anaconda.org/anaconda/mkl) from the `defaults` channel still works.

**Comment by cmutel** [comment]
Based on https://github.com/brightway-lca/brightway2-calc/issues/36#issuecomment-853736502, it seems like you could test for both filenames.

**Comment by haasad** [comment]
see https://github.com/haasad/PyPardisoProject/commit/98701c21ae5d5b9879c51531ace93c2213c89d55
