### ISSUE TITLE
Solver failed with code -2 when running in jupyter notebook

### ISSUE THREAD

**Issue by shushu-qin** [haasad/PyPardisoProject#38]
Hi, 
I am using 0.4.0 version of the package. I tried the simple example in a python script file. It can be run without any error. However, if I run the same code in a jupyter notebook or use pypardiso in a member function of a class, it fails. Can anyone help resolve this issue?

The code I was testing is as follows:
`
import pypardiso
import numpy as np
import scipy.sparse as sp
from scipy.io import loadmat

A = sp.rand(10, 10, density=0.5, format='csr')
b = np.random.rand(10)
x = pypardiso.spsolve(A, b)
print(x)
`

And the error I received is:
![Screenshot from 2022-03-24 15-10-44](https://user-images.githubusercontent.com/24193134/159934968-7e6139b0-af01-447c-a548-01384392edc1.png)

**Comment by shushu-qin** [comment]
Thank you for the reply. I am gonna give as much information as possible 😄 
1. The OS is Ubuntu 20.04.2 LTS.
2. Here is the output of pip list
[pip_list.txt](https://github.com/haasad/PyPardisoProject/files/8345214/pip_list.txt)
3. CPU: 12th Gen Intel(R) Core(TM) i9-12900KF with configuration: cores=16 enabledcores=16 threads=24
4.  The memory of my system is as follows. I think the memory won't be a problem. It's wired to get this error. 
                  total        used        free      shared  buff/cache   available
Mem:          64100        8993        8804         343       46302       54053
Swap:          2047         354        1693

PS: I used to use this library for the same code on an old desktop: Ubuntu 20.04 Intel i5 cores=4, threads=8. It worked. Now I am moving the code to another computer, it gave me the aforementioned error.

**Comment by haasad** [comment]
This looks very similar to what you describe: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/pardiso-insufficient-memory/m-p/1358741#M32717%3Fprofile.language=en

Can you try downgrading `mkl` and `intel-openmp` and see if that changes anything?
```
pip install mkl==2022.0.1 intel-openmp==2022.0.1
```

**Comment by shushu-qin** [comment]
Downgrading `mkl` and `intel-openmp`  doesn't change anything. I circumvented the problem in an inefficient way: save the matrix in a file and start a new process to read the file and perform calculation...
