### ISSUE TITLE
float32 support

### ISSUE THREAD

**Issue by xper0418** [haasad/PyPardisoProject#42]
Hi.
As far as I know, PyPardiso only supports float64.
 I hope to use float32 to save memory.
Any update plans?

**Comment by haasad** [comment]
Hi there, no plans to support float32 as of now. I assume the accuracy of the result will suffer a lot when using float32. Have you tried to solve your system with scipy's spsolve to check if the result is acceptable in terms of accuracy and computation time?

**Comment by xper0418** [comment]
Thanks for the response.
I tested it with sicpy, but the calculation was not finished, so I stopped in the middle. Since I already store the results as a float32, I don't think there will be any accuracy issues.
