### ISSUE TITLE
Licensing Intel oneAPI Math Kernel Library PARDISO 

### ISSUE THREAD

**Issue by parshakova** [haasad/PyPardisoProject#52]
do you know can pypardiso that is interfacing Intel oneAPI Math Kernel Library PARDISO be used for open source projects ?

**Comment by haasad** [comment]
Hi @parshakova,

pypardiso itself is licensed under the [BSD-3-clause license](https://opensource.org/license/bsd-3-clause/): see [LICENSE.txt](https://github.com/haasad/PyPardisoProject/blob/master/LICENSE.txt)

For PARDISO included in Intel MKL, tto my knowledge the `Intel Simplified Software License` applies, see https://cdrdv2-public.intel.com/749362/intel-simplified-license-software-october-2022.pdf

see also:
- https://pypi.org/project/mkl/
- https://anaconda.org/intel/mkl
